version: '3.8'
services:
  frontend:
    build:
      context: frontend
    ports:
      - 8080:8080
    environment:
      VITE_API: ${VITE_API:-http://localhost:3000}
      VITE_API_TIMEOUT: ${VITE_API_TIMEOUT:-30000}
      VITE_COOKIE_TOKEN_NAME: ${VITE_COOKIE_TOKEN_NAME:-web-temps-reel-token}
    # depends_on:
    #   - api

  postgres:
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-root}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
      POSTGRES_DB: ${POSTGRES_DB:-app}
    volumes:
      - ./pg-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${POSTGRES_USER}", "-d", "${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

  mongo:
    image: mongo
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USER:-root}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD:-password}
      MONGO_INITDB_DATABASE: ${MONGO_DB:-app}
    volumes:
      - ./mongo-data:/data/db
    healthcheck:
      test: ["CMD", "mongo", "--username", "${MONGO_ROOT_USER:-root}", "--password", "${MONGO_ROOT_PASSWORD:-password}", "--authenticationDatabase", "admin", "--eval", "db.stats().ok"]
      interval: 10s
      timeout: 5s
      retries: 5
      