version: '3.8'
services:
  frontend:
    build:
      context: frontend
    ports:
      - 8080:8080
    environment:
      VITE_API: ${VITE_API:-http://localhost:3000}
      VITE_API_TIMEOUT: ${VITE_API_TIMEOUT:-30000}
      VITE_COOKIE_TOKEN_NAME: ${VITE_COOKIE_TOKEN_NAME:-web-temps-reel-token}
    depends_on:
      - backend
    env_file:
      - frontend/.env

  postgres:
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-root}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
      POSTGRES_DB: ${POSTGRES_DB:-app}
    volumes:
      - ./pg-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${POSTGRES_USER:-root}", "-d", "${POSTGRES_DB:-app}"]
      interval: 10s
      timeout: 5s
      retries: 5
    env_file:
      - backend/.env

  mongo:
    image: mongo
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME:-root}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD:-password}
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE:-app}
    volumes:
      - ./mongo-data:/data/db
    env_file:
      - backend/.env

  backend:
    build:
      context: backend
    ports:
      - 3000:3000
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-root}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
      POSTGRES_DB: ${POSTGRES_DB:-app}
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME:-root}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD:-password}
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE:-app}
      JWT_SECRET: ${JWT_SECRET:-secret}
      FRONTEND_URL: ${FRONTEND_URL:-http://localhost:8080}
      BASE_PATH: ${BASE_PATH:-/}
      MONGO_DATABASE_SERVICE_SERVICE_HOST: mongo
      POSGRES_DATABASE_SERVICE_SERVICE_HOST: postgres
    depends_on:
      postgres:
        condition: service_healthy
      mongo:
        condition: service_started
    env_file:
      - backend/.env
    command: ["sh", "start.sh"]
    