apiVersion: apps/v1
kind: Deployment
metadata:
  name: posgres-database-deployment
  namespace: web-temps-reel
spec:
  replicas: 1
  selector:
    matchLabels:
      app: posgres-database
  template:
    metadata:
      labels:
        app: posgres-database
    spec:
      containers:
        - name: posgres-database
          image: postgres:15.4-alpine
          ports:
          - containerPort: 5432
          volumeMounts:
          - name: posgres-database-data
            mountPath: /var/lib/postgresql/data
          envFrom:
          - secretRef:
              name: database-secrets
      volumes:
      - name: posgres-database-data
        hostPath:
          path: /home/ubuntu/app/pg-data-web-temps-reel

---

apiVersion: v1
kind: Service
metadata:
  name: posgres-database-service
  namespace: web-temps-reel
spec:
  selector:
    app: posgres-database
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
