apiVersion: batch/v1
kind: Job
metadata:
  name: posgres-migration-job
  namespace: marmiton
spec:
  template:
    spec:
      containers:
        - name: posgres-migration-container
          image: gatien1/marmiton-backend:latest
          command:
            - npx
            - posgres
            - migrate
            - deploy
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: database-info
                  key: URL
      restartPolicy: Never