apiVersion: v1
kind: Secret
metadata:
  name: database-secrets
  namespace: web-temps-reel
type: Opaque
stringData:
  POSTGRES_USER: "root"
  POSTGRES_PASSWORD: "password"
  POSTGRES_DB: "app"
  MONGO_ROOT_USER: "root"
  MONGO_ROOT_PASSWORD: "password"
  MONGO_DB: "app"

---

apiVersion: v1
kind: Secret
metadata:
  name: backend-secrets
  namespace: web-temps-reel
type: Opaque
stringData:
  FRONTEND_URL: "https://quizz.bliblablou.day/"
