name: Backend tests
run-name: ${{ github.actor }} launching backend tests

on:
  pull_request:
    branches: [ main ]
    paths:
      - 'backend/**'
      - '.github/workflows/deploy-backend.yml'
    
jobs:
  eslint:
    name: Eslint (backend)
    defaults:
      run:
        working-directory: backend
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '21'
      - name: Install eslint
        run: npm install eslint
      - name: Launch eslint
        run: npm run lint
  build:
    needs: 
      - eslint
    runs-on: ubuntu-latest
    name: Build (backend)
    defaults:
      run:
        working-directory: backend
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '21'
      - name: Install dependencies
        run: npm install
      - name: Build
        run: npm run build
