name: Deploy frontend to VPS
run-name: ${{ github.actor }} deployed frontend to VPS (${{ github.sha }})

on:
  push:
    branches: [ main ]
    paths:
      - 'frontend/**'
      - '.github/workflows/deploy-frontend.yml'
      - 'kubernetes/frontend-deploy-and-service.yaml'

env:
  DOCKERHUB_REPO_FRONTEND: ${{ vars.DOCKERHUB_USERNAME }}/web-temps-reel-frontend

jobs:
  publish_frontend:
    runs-on: ubuntu-latest
    name: Publish frontend image
    environment:
      name: production
    steps:
      - uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Create .env.production file to with correct API URL
        # Replace VITE_API line with the production URL
        run: sed "s#VITE_API=.*#VITE_API=${{ vars.URL }}api#g" .env.example > .env.production
        working-directory: ./frontend
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: "./frontend"
          push: true
          tags: ${{ env.DOCKERHUB_REPO_FRONTEND }}:latest, ${{ env.DOCKERHUB_REPO_FRONTEND }}:${{ github.sha }}

  deploy_frontend:
    runs-on: ubuntu-latest
    name: Deploy frontend
    needs:
      - publish_frontend
    environment:
      name: production
      url: ${{ vars.URL }}
    concurrency: deploy
    steps:
      - uses: actions/checkout@v3
      - name: Set up kubectl
        run: |
          mkdir -p ~/.kube
          echo "${{ secrets.KUBECONFIG }}" > ~/.kube/config
      - name: Redeploy
        run: |
          kubectl set image deployment/frontend-deployment front=${{ env.DOCKERHUB_REPO_FRONTEND }}:${{ github.sha }} -n web-temps-reel
          kubectl rollout status deployment/frontend-deployment -n web-temps-reel
